"""Pinned public-source declarations for Nano pretraining proposals."""

from __future__ import annotations

from copy import deepcopy


TINYSTORIES_REVISION = "f54c09fd23315a6f9c86f9dc80f725de7d8f9c64"
FINEWEB_EDU_REVISION = "87f09149ef4734204d70ed1d046ddc9ca3f2b8f9"

SOURCES: dict[str, dict] = {
    "tinystories": {
        "dataset_name": "roneneldan/TinyStories",
        "dataset_version": f"hf-revision-{TINYSTORIES_REVISION}",
        "location_type": "publicly_downloadable_synthetic",
        "source_uri": "https://huggingface.co/datasets/roneneldan/TinyStories",
        "source_revision": TINYSTORIES_REVISION,
        "config": "default",
        "license": {
            "identifier": "cdla-sharing-1.0",
            "publisher_declared": True,
            "permitted_use": "internal Nano research and model training under the declared license",
            "commercial_clearance": "not_reviewed",
            "notice": "Preserve provenance and comply with the publisher-declared CDLA Sharing 1.0 terms.",
        },
        "provenance": "synthetically generated by the publisher using GPT-3.5 and GPT-4",
        "source_files": [
            {
                "split": "train",
                "path": "data/train-00000-of-00004-2d5a1467fff1081b.parquet",
                "bytes": 248_731_111,
                "sha256": "77cf780cebe52b6e83e3a2ac84bc56d8059363113e41d17a023f1d8b2ed0fc0b",
            },
            {
                "split": "train",
                "path": "data/train-00001-of-00004-5852b56a2bd28fd9.parquet",
                "bytes": 248_171_980,
                "sha256": "e2f173a6dcc2b5895183e8ad376e115bd5c06764eb0cfc01ce1add156b2d017f",
            },
            {
                "split": "train",
                "path": "data/train-00002-of-00004-a26307300439e943.parquet",
                "bytes": 245_894_874,
                "sha256": "cac73cd1a0973a7fccde022a5a5c78f8ba58ea6849541835c58e7c5fc747f2ef",
            },
            {
                "split": "train",
                "path": "data/train-00003-of-00004-d243063613e5a057.parquet",
                "bytes": 247_988_350,
                "sha256": "862514ae75723ddd339337f1ef7617b88f82290dcddd57445e1d38d257ca7891",
            },
            {
                "split": "validation",
                "path": "data/validation-00000-of-00001-869c898b519ad725.parquet",
                "bytes": 9_989_127,
                "sha256": "33406a6206554cfc279c29c11f4df51528af487aa1a602b075566fc83c49dcab",
            },
        ],
        "source_file_count": 5,
        "source_total_bytes": 1_000_775_442,
        "split_definition": {
            "train": "publisher train split, prefix streamed in source order until the declared token budget",
            "validation": "publisher validation split, prefix streamed in source order until the declared token budget",
            "test": "none; Nano capability evaluation data is excluded and remains evaluation-only",
        },
        "authorization_state": "approved_for_bounded_local_smoke",
        "private_or_development_data": False,
    },
    "fineweb-edu": {
        "dataset_name": "HuggingFaceFW/fineweb-edu",
        "dataset_version": f"sample-10BT@{FINEWEB_EDU_REVISION}",
        "location_type": "publicly_downloadable_web_corpus",
        "source_uri": "https://huggingface.co/datasets/HuggingFaceFW/fineweb-edu",
        "source_revision": FINEWEB_EDU_REVISION,
        "config": "sample-10BT",
        "license": {
            "identifier": "odc-by-1.0",
            "publisher_declared": True,
            "permitted_use": "proposal-stage internal research, subject to ODC-By, Common Crawl terms, and source-content rights",
            "commercial_clearance": "blocked_pending_review",
            "notice": "The dataset card warns that source web content can carry separate rights and harmful or biased material.",
        },
        "provenance": "English Common Crawl pages filtered by the publisher's educational-quality classifier (score >= 3)",
        "source_files": [
            {"path": "sample/10BT/000_00000.parquet", "bytes": 2_152_819_114, "sha256": "b1ba7b2ce4cb5ea6ef42dca40263eabb85f37700d01693a68e9b30a31d78e871"},
            {"path": "sample/10BT/001_00000.parquet", "bytes": 2_152_222_432, "sha256": "3fcf2dc69cd52503986276d3d2d26a8c356d0f2ea28a0de4fdbda8cf87755693"},
            {"path": "sample/10BT/002_00000.parquet", "bytes": 2_151_796_315, "sha256": "547ae182d132c9f06b6ce63149567208ea9f57630bfd9b1a2938e504f0c9ebd7"},
            {"path": "sample/10BT/003_00000.parquet", "bytes": 2_152_437_524, "sha256": "22184e6eb25759ddd97783751ffc73e1705dfa2542e630dae1f2a8bac8ee6ddb"},
            {"path": "sample/10BT/004_00000.parquet", "bytes": 2_152_338_550, "sha256": "33557ddd87a07a4ae6fcaf7a4789c7b484e5cc0c273ca12a65b74200e6d8748b"},
            {"path": "sample/10BT/005_00000.parquet", "bytes": 2_152_189_947, "sha256": "e08d79927ecb377786572cd854817c748ceb8880878b1a0eb91abf8c85d505ea"},
            {"path": "sample/10BT/006_00000.parquet", "bytes": 2_152_689_867, "sha256": "554fa2613c9261d6c9c396caab881de3160175794c6c3e1856bf28a0e9cb9b76"},
            {"path": "sample/10BT/007_00000.parquet", "bytes": 2_150_686_637, "sha256": "4b7d1f697d4afff7f5f65cb7aa4d83acc6db716da4d46ea23399d0c50608c6e3"},
            {"path": "sample/10BT/008_00000.parquet", "bytes": 2_151_274_846, "sha256": "a6d9dcc0c72ecd7c7f0173c2d06b3a4249a2ccaa94961469d1a522ca689bbf1a"},
            {"path": "sample/10BT/009_00000.parquet", "bytes": 2_151_913_277, "sha256": "f836cd3c70b95776699eb6c356b2dbf702816e25dcf39992f5c80a29029d23c3"},
            {"path": "sample/10BT/010_00000.parquet", "bytes": 2_152_798_864, "sha256": "e5a2eae25f057f0856a10bfae314c6ca8ea8bb08456d2131e9e89b2b8305e2f6"},
            {"path": "sample/10BT/011_00000.parquet", "bytes": 2_152_323_681, "sha256": "db71cf0425bb3d1813a09f12ff1acd6dabdfb91a2e4f141960254ee5a7f036e7"},
            {"path": "sample/10BT/012_00000.parquet", "bytes": 2_152_069_689, "sha256": "08b47a3e1c25161f796d2f8dbf99ccf60affdebdcea4910833d0d5783315551f"},
            {"path": "sample/10BT/013_00000.parquet", "bytes": 540_632_672, "sha256": "b393f51fefab26cd6f4c8f65707c1924f6666c4961a0ebebe04bb57f7ec832de"},
        ],
        "source_file_count": 14,
        "source_total_bytes": 28_518_193_415,
        "split_definition": {
            "train": "documents with sha256(UTF-8 text) modulo 1000 >= 10",
            "validation": "documents with sha256(UTF-8 text) modulo 1000 < 10",
            "test": "none; frozen Nano/H6 and all development evaluation artifacts are excluded",
        },
        "authorization_state": "proposal_only",
        "blocking_gates": [
            "approve source-content and commercial-use risk"
            " [OWNER-BLOCKED; question recorded in papers/DATA_LICENSES.md section 4]",
            "freeze a contamination exclusion digest set"
            " [POLICY DEFINED 2026-08-04 in papers/DATA_LICENSES.md section 3;"
            " digest computation deferred to the authorized preparation run"
            " because hashing sealed partitions is itself a read]",
            "resolve and hash the exact pinned source-file inventory"
            " [SATISFIED 2026-08-04: 14 parquet files with per-file sha256"
            " recorded in this declaration]",
            "complete a bounded local preparation run and verify its manifest"
            " [BLOCKED BEHIND the owner gate; prepare.py refuses proposal_only]",
        ],
        "private_or_development_data": False,
    },
}


def source_record(name: str) -> dict:
    """Return a mutable copy of a supported source declaration."""

    try:
        return deepcopy(SOURCES[name])
    except KeyError as exc:
        raise ValueError(f"unsupported dataset: {name}") from exc
